### ISSUE TITLE
Hey trying to build PHRSR but...

### ISSUE THREAD

**Issue by CIRCUITF0RGE** [supersynthesis/eurorack#2]
...i can't find some values for the caps for example? Would you let me know which values are the missing ones or update the BOM?
Awesome modules btw

**Comment by supersynthesis** [comment]
ah, I will update the schematic! but for you right now, all unlabeled caps are 100nf, they're just decoupling caps

**Comment by CIRCUITF0RGE** [comment]
thanks

**Comment by CIRCUITF0RGE** [comment]
and the pots are 100K ?

**Comment by supersynthesis** [comment]
schematic updated! pots are 10k. diodes are all 1N4148, regulator is AMS1117-3.3

**Comment by CIRCUITF0RGE** [comment]
Sweet ... thank you very much...

**Comment by CIRCUITF0RGE** [comment]
so i build the stuff in STM32IDE and run it and it throw no errors but still doesn't work...not sure what i am doin wrong and don't want to stress u too much but do u have a compiled file for it maybe...just want to rule out hardware error since i soldered it by myself

**Comment by supersynthesis** [comment]
hmm! yes here is the .elf 
https://github.com/supersynthesis/eurorack/blob/main/Production%20Modules/PHRSR/firmware/PHRSR_V4/Debug/PHRSR_V4.elf

**Comment by supersynthesis** [comment]
sorry to hear you're having troubles. tell me more about your hardware. is this with a custom PCB? and what do you mean when you say doesn't work?

**Comment by CIRCUITF0RGE** [comment]
yeah i made 5boards at jlc and trying to get it work from your GitHub ...i think i programmed it but seems the TL072C i am using are shitte or i am using the wrong chip lol?

**Comment by CIRCUITF0RGE** [comment]
converted the do-trace to kicad and can't see a description at U5 and the lower too it says TL0 so i thought its a TL072>?

**Comment by stilltryin** [comment]
maybe drop me an email stillkingz@gmail.com and we go on have a chat there
